### PR TITLE
add support for policy remove

### PR DESCRIPTION
**Pull request by svt-kmcdaniel**
* implemented the policy delete request.

Signed-off-by: Ken McDaniel <kenneth.mcdaniel@hpe.com>

### CODE REVIEW

**Review by sijeesh — COMMENTED** [review]
Add an example for delete operation in the example file of policy resource.
The idea is to keep at least one example of all the features available for a resource.

**Comment by svt-kmcdaniel** [comment]
> Add an example for delete operation in the example file of policy resource.
> The idea is to keep at least one example of all the features available for a resource.

Can this be postponed in the example script until we have a policy create example?

I am hesitant implementing a policy delete in an example script that could be executed against a customer box that would change the environment permanently.

Once I get the policy create implemented, I would feel more comfortable creating a policy, and then deleting that policy in the example script.

**Comment by sijeesh** [comment]
> > Add an example for delete operation in the example file of policy resource.
> > The idea is to keep at least one example of all the features available for a resource.
> 
> Can this be postponed in the example script until we have a policy create example?
> 
> I am hesitant implementing a policy delete in an example script that could be executed against a customer box that would change the environment permanently.
> 
> Once I get the policy create implemented, I would feel more comfortable creating a policy, and then deleting that policy in the example script.

Agree with you, let's add the create and delete examples when we have support for both the operations.

**Review by sijeesh — APPROVED** [review]
LGTM

**Comment by sijeesh** [comment]
@svt-kmcdaniel , Missed one thing,
Please update endpoint support file with the delete operation support https://github.com/HewlettPackard/simplivity-python/blob/master/endpoints-support.md

**Review by sijeesh — APPROVED** [review]
LGTM

**Pull request merged**
